export enum PATHS {
  "LOGIN" = "LOGIN",
  "REGISTER" = "REGISTER",
  "ACCOUNT" = "ACCOUNT",
  "HOME" = "Home",
  "LEADERBOARD" = "LEADERBOARD",
  "SETTINGS" = "SETTINGS",
  "PLAY" = "PLAY",
  "EDIT_PROFILE" = "EditProfile",
  "JOIN" = "JOIN",
  "MAPS" = "MAPS",
  "FINISHED_TREASURES" = "FINISHED_TREASURES",
}
